In [59]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
from gspread_pandas import Spread, conf

In [60]:
config_path = r'C:\Users\USER\Downloads\Emarath_global\service_account.json'
# 3. Define the Sheet URL (Name - EMARATH GLOBAL -DASHBOARD)
emarath_global_sheet_url = "https://docs.google.com/spreadsheets/d/1aXobnCl4QQ-hQ_IWoTPo2ZEo3HM5kNwycwMBJtEDOfc/edit?gid=822921427#gid=822921427"
# Load the config from your service account JSON
c = conf.get_config(file_name=config_path)

# Connect using that config object
emarath_spread = Spread(emarath_global_sheet_url, config=c)

In [61]:
master_df = pd.read_excel(r'C:\Users\USER\Downloads\Emarath_global\Data\flowbee_detaild_report.xlsx', skiprows=4)
master_df

,AGENT_NAME,CUSTOMER_NAME,MOBILE,EMAIL,STATUS,CONTACT_SOURCE,SOURCE_ID,SOURCE_URL,CREATE_DATE
0,NaN,Jony,966502618310,NaN,OPEN,ad,6.947847e+12,https://fb.me/9LTAQ7gmB,NaN
1,NaN,mughal6978053,966549198493,NaN,OPEN,ad,6.947740e+12,https://fb.me/bequ8XZlH,NaN
2,NaN,mohammedmuzammil9061,966573073812,NaN,OPEN,ad,6.947738e+12,https://www.instagram.com/p/DUJczOvAGG-/,NaN
3,NaN,Sohaib Nawab,966580898680,NaN,OPEN,ad,6.947312e+12,https://fb.me/3ZqzV6FYb,NaN
4,ADHIL C K,afnasappu1441,917510962030,NaN,OPEN,ad,1.202369e+17,https://www.instagram.com/p/DUG0HIaAHQW/,NaN
...,...,...,...,...,...,...,...,...,...
87,SUSHANTHIKA E,🅼🅷🅳 🅰🅽🅰🆂,94763260943,NaN,OPEN,ad,6.951400e+12,https://fb.me/4cxrQM0U1,NaN
88,SUSHANTHIKA E,Usman Saristar,966561597232,NaN,OPEN,ad,6.948871e+12,https://fb.me/7nTAUUJoY,NaN
89,SUSHANTHIKA E,Mati Ur Rehman,966590230741,NaN,OPEN,ad,6.948871e+12,https://fb.me/jpuQGNZ10,NaN
90,ZAKIYA GAFOOR,firdousnisam45,966540853430,NaN,OPEN,ad,1.202369e+17,https://fb.me/4aGAfuIvC,NaN
91,ZAKIYA GAFOOR,Amir Khan,971562236412,NaN,OPEN,ORGANIC,NaN,NaN,NaN

In [62]:
# 5. Loop through and pull categorized data
all_data_list = []
all_sheets = emarath_spread.sheets

# Define exactly which statuses you want to track
target_date = "2026-11-02" 

for sheet in all_sheets:
    sheet_name = sheet.title
    
    if sheet_name in ["MAIN DASHBOARD", "CRM", "Dropdowns", "Sheet1", "DASHBOARD", "20"]:
        continue
    
    try:
        df = emarath_spread.sheet_to_df(sheet=sheet_name, index=None, header_rows=1)
        
        if not df.empty and all(col in df.columns for col in ['DATE', 'NAME', 'PHONE NO 1']):
      
            df['DATE'] = pd.to_datetime(df['DATE'], errors='coerce')

            mask = df['DATE'].dt.date == pd.to_datetime(target_date).date()
            filtered_df = df[mask].copy()
            
            if not filtered_df.empty:
                filtered_df['Name of BDE'] = sheet_name
                filtered_df['DATE'] = filtered_df['DATE'].dt.strftime('%Y-%d-%m')
                all_data_list.append(filtered_df[['DATE', 'Name of BDE', 'NAME', 'PHONE NO 1']])
            
    except Exception as e:
        print(f"Skipping {sheet_name}: {e}")

In [63]:
df

,REF NO,COUNTRY,DATE,AGENT,CUSTOMER PATH,NAME,PHONE NO 1,PHONE NO 2,1,2,...,PRODUCT 2,QTY,VALUE,PAYMENT\nMETHOD,LEAD SOURCE,DISPATCH,DISPATCH DATE,AGENT \nNAME,CS REMARKS,VENDOR
0,EMCR21501,KSA,2026-06-02,SAFAN,LEAD,Sukur Ali\n\n,966538937099,,TRUE,TRUE,...,,,,,,,,,,
1,EMCR21502,KSA,2026-06-02,SAFAN,LEAD,,966562674066,,TRUE,TRUE,...,,,,,,,,,,
2,EMCR21503,KSA,2026-06-02,SAFAN,LEAD,rahman,966501457705,,TRUE,TRUE,...,,,,,,,,,,
3,EMCR21504,KSA,2026-06-02,SAFAN,LEAD,shaheen,966597262271,,TRUE,TRUE,...,,,,,,,,,,
4,EMCR21505,KSA,2026-06-02,SAFAN,LEAD,mirzan,966530149233,,TRUE,TRUE,...,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,EMCR22496,,NaT,,,,,,FALSE,FALSE,...,,,,,,,,,,
996,EMCR22497,,NaT,,,,,,FALSE,FALSE,...,,,,,,,,,,
997,EMCR22498,,NaT,,,,,,FALSE,FALSE,...,,,,,,,,,,
998,EMCR22499,,NaT,,,,,,FALSE,FALSE,...,,,,,,,,,,
999,EMCR22500,,NaT,,,,,,FALSE,FALSE,...,,,,,,,,,,

In [72]:
all_data_list

[           DATE Name of BDE               NAME    PHONE NO 1
 149  2026-02-11      SHABNA           babu bai  966560811910
 150  2026-02-11      SHABNA        maroof azmi  966557041766
 151  2026-02-11      SHABNA            wengnoi  966555437026
 152  2026-02-11      SHABNA         iztaraizes  966531861585
 153  2026-02-11      SHABNA               OMIN  966580292406
 154  2026-02-11      SHABNA  HIGHRANGE Emperor  966501058690,
            DATE Name of BDE                  NAME     PHONE NO 1
 137  2026-02-11       ADHIL        muhammadzahoor   923023790838
 138  2026-02-11       ADHIL          mdtoufikuli7  8801775983925
 139  2026-02-11       ADHIL                  Haei   919118695928
 140  2026-02-11       ADHIL             balverk65   966571739884
 141  2026-02-11       ADHIL                  وسیم   966598304015
 142  2026-02-11       ADHIL            Suresh sah   966571838240
 143  2026-02-11       ADHIL         SAIFUDHEEN CK   966502285184
 144  2026-02-11       ADHIL            Tuhin Azad   966532926735
 145  2026-02-11       ADHIL                albert   917825091406
 146  2026-02-11       ADHIL            harshad tm   966544485127
 147  2026-02-11       ADHIL                aminah   966536203424
 148  2026-02-11       ADHIL  الحمدلله دائما وابدا   966553736396
 149  2026-02-11       ADHIL                  rana   966593052491
 150  2026-02-11       ADHIL         afnasappu1441   917510962030
 151  2026-02-11       ADHIL                         919037709835
 152  2026-02-11       ADHIL       bhoomibhooinath   966559622587,
            DATE Name of BDE                   NAME    PHONE NO 1
 134  2026-02-11     FARSANA  Ankomha Abigail\r\n\r  966590760434
 135  2026-02-11     FARSANA            ummu khalid  966595816607
 136  2026-02-11     FARSANA                rafeek   919746729430
 137  2026-02-11     FARSANA                   raja  966530829948
 138  2026-02-11     FARSANA            Ashish Babu  966507485453
 139  2026-02-11     FARSANA   محمد علي مرتضى\r\n\r  966594654049
 140  2026-02-11     FARSANA                  SETHU  918547407774
 141  2026-02-11     FARSANA          Jubaed Jubaed  966535700546,
            DATE Name of BDE                 NAME     PHONE NO 1
 132  2026-02-11      SHAMNA                Ni Ni   966598703238
 133  2026-02-11      SHAMNA                 omar   967730237435
 134  2026-02-11      SHAMNA                  ali   966534698372
 135  2026-02-11      SHAMNA             Vishahad   966568077906
 136  2026-02-11      SHAMNA           AZMAT SHER   966591981526
 137  2026-02-11      SHAMNA               rizwan   966575308704
 138  2026-02-11      SHAMNA                        966571273507
 139  2026-02-11      SHAMNA        Nowsath Fathi   918122150355
 140  2026-02-11      SHAMNA               bongca   639818140445
 141  2026-02-11      SHAMNA                Kabir  8801345779601
 142  2026-02-11      SHAMNA  Shayad Faisal Ahmed   966535274914
 143  2026-02-11      SHAMNA              Charles   918610771709
 144  2026-02-11      SHAMNA               Vinod      0536381362
 145  2026-02-11      SHAMNA           S Mohideen   966508864441
 146  2026-02-11      SHAMNA        Hussainar Abu   966599123980
 147  2026-02-11      SHAMNA           Sajid Khan   966580819004
 148  2026-02-11      SHAMNA                        966538651269,
            DATE Name of BDE                     NAME    PHONE NO 1
 159  2026-02-11  CHAITHANYA          Zaid Khan\r\n\r  923059296028
 160  2026-02-11  CHAITHANYA  Shahnawaz Hussain\r\n\r  966507473429
 161  2026-02-11  CHAITHANYA    Saqib Awan 🇵🇰🇸🇦\r\n\r  966558073455
 162  2026-02-11  CHAITHANYA     محمد زبير احمد\r\n\r  966534248816
 163  2026-02-11  CHAITHANYA           Mama Ppp\r\n\r  256788330017
 164  2026-02-11  CHAITHANYA         Shafeeq MK\r\n\r  966509456711
 165  2026-02-11  CHAITHANYA              Banaras Ali  966576438279
 166  2026-02-11  CHAITHANYA             omarelshriaf  966594669078
 167  2026-02-11  CHAITHANYA                    Jasim  966558423840
 168  2026-02-11  CHAITHANYA     اريد زوجة تصلي\r\n\r  966578031729
 169  2026-02-11  CHAITHANYA           Md Rakib\r\n\r  966545865957
 170  2026-02-11  CHAITHANYA        Angel Sanam\r\n\r  923094979314,
            DATE Name of BDE                  NAME    PHONE NO 1
 165  2026-02-11        NEHA          Sultan Monir  966504138356
 166  2026-02-11        NEHA             Lalazaman  966570558057
 167  2026-02-11        NEHA    joynal uddin opu78  966550172114
 168  2026-02-11        NEHA  عبد الباسط الميرفابي  966544726938
 169  2026-02-11        NEHA        Susan Enriquez  966544570149
 170  2026-02-11        NEHA              MD Hanif  966544569204
 171  2026-02-11        NEHA           Asif Khatri  966539070233
 172  2026-02-11        NEHA
 173  2026-02-11        NEHA
 174  2026-02-11        NEHA
 175  2026-02-11        NEHA
 176  2026-02-11        NEHA
 177  2026-02-11        NEHA
 178  2026-02-11        NEHA
 179  2026-02-11        NEHA                                    ,
            DATE Name of BDE         NAME    PHONE NO 1
 180  2026-02-11     BURHANA        Goryo  966510790997
 181  2026-02-11     BURHANA   Neema June  254741107544
 182  2026-02-11     BURHANA  Rahed~ Babu  966561418455
 183  2026-02-11     BURHANA   Midul Khan  966544670396
 184  2026-02-11     BURHANA     PRASANNA  966531438713,
            DATE Name of BDE                 NAME     PHONE NO 1
 142  2026-02-11       AMINA            Abu💓Sumee   919043951969
 143  2026-02-11       AMINA             ابو بلال   966508525345
 144  2026-02-11       AMINA        \r\nM.Shakeel   966581289657
 145  2026-02-11       AMINA         Aatif Rizwan  9779845889878
 146  2026-02-11       AMINA                 D. A   966576614807
 147  2026-02-11       AMINA  rasheedahmed 993 pk   923118360103
 148  2026-02-11       AMINA     ابو خطاب العولقي   966502508627
 149  2026-02-11       AMINA          جميل انصاري   966544542216
 150  2026-02-11       AMINA           rashad6689   966571952364
 151  2026-02-11       AMINA     Rahul P Krishnan   966535048434
 152  2026-02-11       AMINA     Sannylyn Asuzina   966555026379
 153  2026-02-11       AMINA        Md Arman Khan   966578976814
 154  2026-02-11       AMINA        haseebsmart08   966571087829
 155  2026-02-11       AMINA       MOHAMMED USMAN   966561724163
 156  2026-02-11       AMINA               SHAJIR   966596096776
 157  2026-02-11       AMINA               SHAJIR   966596096776,
            DATE Name of BDE            NAME     PHONE NO 1
 154  2026-02-11        ARUN           تسليم    94777185600
 155  2026-02-11        ARUN       neyaz1003   966567426595
 156  2026-02-11        ARUN             nil  8801817374837
 157  2026-02-11        ARUN              55   966511495247
 158  2026-02-11        ARUN  Ziad Al-Najjar   966544462036
 159  2026-02-11        ARUN
 160  2026-02-11        ARUN
 161  2026-02-11        ARUN
 162  2026-02-11        ARUN
 163  2026-02-11        ARUN
 164  2026-02-11        ARUN
 165  2026-02-11        ARUN
 166  2026-02-11        ARUN
 167  2026-02-11        ARUN
 168  2026-02-11        ARUN
 169  2026-02-11        ARUN
 170  2026-02-11        ARUN
 171  2026-02-11        ARUN
 172  2026-02-11        ARUN
 173  2026-02-11        ARUN
 174  2026-02-11        ARUN
 175  2026-02-11        ARUN
 176  2026-02-11        ARUN
 177  2026-02-11        ARUN
 178  2026-02-11        ARUN
 179  2026-02-11        ARUN
 180  2026-02-11        ARUN
 181  2026-02-11        ARUN                               ,
            DATE Name of BDE                  NAME    PHONE NO 1
 109  2026-02-11       RAHIB              SHAMSMIR  966582538905
 110  2026-02-11       RAHIB     KHAN SHARAFUDHEEN  966543527039
 111  2026-02-11       RAHIB                   HHH  923003097778
 112  2026-02-11       RAHIB            SUBAIR M K  966502838954
 113  2026-02-11       RAHIB          ASHAR NEERAD  966502912410
 114  2026-02-11       RAHIB  Bandula Kumarasinghe  966571420816
 115  2026-02-11       RAHIB              DEW SOUL  917736598809
 116  2026-02-11       RAHIB           RAYAD AHMED  966580889371
 117  2026-02-11       RAHIB                 ALAMG  966502038178
 118  2026-02-11       RAHIB    MUHAMMED FAHAD B K  966559043786,
            DATE Name of BDE            NAME    PHONE NO 1
 135  2026-02-11      HABIYA                  916282116690
 136  2026-02-11      HABIYA  Aneesh Perunad  966531341232
 137  2026-02-11      HABIYA
 138  2026-02-11      HABIYA
 139  2026-02-11      HABIYA
 140  2026-02-11      HABIYA
 141  2026-02-11      HABIYA
 142  2026-02-11      HABIYA
 143  2026-02-11      HABIYA
 144  2026-02-11      HABIYA
 145  2026-02-11      HABIYA
 146  2026-02-11      HABIYA
 147  2026-02-11      HABIYA                              ,
           DATE Name of BDE      NAME    PHONE NO 1
 47  2026-02-11  SUHANTHIKA  🅼🅷🅳 🅰🅽🅰🆂   94763260943
 48  2026-02-11  SUHANTHIKA    Arshad   94779000608
 49  2026-02-11  SUHANTHIKA     emran  966533252921
 50  2026-02-11  SUHANTHIKA   mnhorah  966508740278
 51  2026-02-11  SUHANTHIKA      ❤️‍🩹  919567074664
 52  2026-02-11  SUHANTHIKA
 53  2026-02-11  SUHANTHIKA
 54  2026-02-11  SUHANTHIKA
 55  2026-02-11  SUHANTHIKA                        ,
           DATE Name of BDE                  NAME     PHONE NO 1
 49  2026-02-11        NAJA      Mohammad MH RONY   966565967720
 50  2026-02-11        NAJA                 Jeeva   966504457416
 51  2026-02-11        NAJA         Ali Sofor ali   966581606212
 52  2026-02-11        NAJA                 Nazim   966509357928
 53  2026-02-11        NAJA             ia9122923   923353172317
 54  2026-02-11        NAJA       ابو مازن السلفي   966534985644
 55  2026-02-11        NAJA        باسم عبدالحميد   966570441984
 56  2026-02-11        NAJA  dhasarathanannamalai   966576316302
 57  2026-02-11        NAJA           shuvrodev37  8801959610959
 58  2026-02-11        NAJA              Md Limon   966539579561,
           DATE  Name of BDE                    NAME    PHONE NO 1
 50  2026-02-11  HIBA SHERIN                  Shizad  923127766624
 51  2026-02-11  HIBA SHERIN               mv6871004  966543800635
 52  2026-02-11  HIBA SHERIN            sam sa121344  917481956665
 53  2026-02-11  HIBA SHERIN           أكرم حسين 🥰🇸🇦  966506468807
 54  2026-02-11  HIBA SHERIN          Mohammad Falah  966552800492
 55  2026-02-11  HIBA SHERIN                  Hashmi  966557368215
 56  2026-02-11  HIBA SHERIN               FAIZ KHAN  966557368215
 57  2026-02-11  HIBA SHERIN        michellebulisig1  639534821903
 58  2026-02-11  HIBA SHERIN             Sajjad Ahme  966577571729
 59  2026-02-11  HIBA SHERIN  MD Mustofa kamal Shuvo  966500897265
 60  2026-02-11  HIBA SHERIN                                      ,
           DATE Name of BDE             NAME    PHONE NO 1
 53  2026-02-11      ZAKIYA  احمر داجا قادري  966571170716
 54  2026-02-11      ZAKIYA           tekiye  966583775651
 55  2026-02-11      ZAKIYA           waseem  966592795951
 56  2026-02-11      ZAKIYA     Parvez Ahmad  966571187331
 57  2026-02-11      ZAKIYA       abhijithem  918129793587
 58  2026-02-11      ZAKIYA           Suhail  966559871382
 59  2026-02-11      ZAKIYA  heshamramdan718  966595068634
 60  2026-02-11      ZAKIYA            usman  923481936849
 61  2026-02-11      ZAKIYA        Amir Khan  971562236412
 62  2026-02-11      ZAKIYA  heshamramdan718  966595068634
 63  2026-02-11      ZAKIYA
 64  2026-02-11      ZAKIYA                               ,
           DATE Name of BDE                  NAME    PHONE NO 1
 65  2026-02-11        AJIN            H.🌹H\r\n\r  966532351907
 66  2026-02-11        AJIN          haketcabajar  639456910842
 67  2026-02-11        AJIN             😀\r\n\r\n  916388673791
 68  2026-02-11        AJIN                 James  254790340633
 69  2026-02-11        AJIN           Naeem Malik  923160850360
 70  2026-02-11        AJIN       janarshadkhan28  966590447817
 71  2026-02-11        AJIN                  رستم  966573253864
 72  2026-02-11        AJIN  Sardar Raees Pardesi  971565830829
 73  2026-02-11        AJIN   Abdel Halim Mustafa  966541874426,
           DATE Name of BDE             NAME     PHONE NO 1
 67  2026-02-11       SAFAN   rashiirashidkm   919746219828
 68  2026-02-11       SAFAN    Danish Ansari   966542601502
 69  2026-02-11       SAFAN   sudheer subair   966538561816
 70  2026-02-11       SAFAN   sharoosharooq6   919945619313
 71  2026-02-11       SAFAN            فرحان   966599819464
 72  2026-02-11       SAFAN              شام   966578077692
 73  2026-02-11       SAFAN  Vijesh Mullakal   971521602642
 74  2026-02-11       SAFAN    Md Rabbi 🇸🇦🇸🇦   966560956978
 75  2026-02-11       SAFAN    shakerhasmiyt   966550921173]

In [73]:
import pandas as pd

if all_data_list:
    final_df = pd.concat(all_data_list, ignore_index=True)
    final_df = final_df.dropna(subset=['NAME', 'PHONE NO 1'])
    
    # Optional: Remove rows where strings might be empty spaces
    final_df = final_df[final_df['NAME'].astype(str).str.strip() != ""]
    final_df = final_df[final_df['PHONE NO 1'].astype(str).str.strip() != ""]

    # final_df = final_df.drop_duplicates(subset=['NAME', 'PHONE NO 1'], keep='first')

    print(f"Successfully merged. Total unique valid records: {len(final_df)}")
else:
    print("No data found matching the criteria.")
    final_df = pd.DataFrame()

Successfully merged. Total unique valid records: 153

In [66]:
# # Check if the list actually has data before merging
# if all_data_list:
#     final_df = pd.concat(all_data_list, ignore_index=True)
#     print(f"Successfully merged {len(all_data_list)} sheets.")
# else:
#     print("No data found matching the criteria.")
#     final_df = pd.DataFrame() # Create an empty DF to avoid errors later

In [74]:
final_df.to_excel("final_df.xlsx")

In [75]:
len(final_df)

153

In [76]:
len(master_df)

92

In [ ]:
final_df = final_df.dropna(subset=['NAME', 'PHONE NO 1'])


final_df['PHONE NO 1'] = final_df['PHONE NO 1'].astype(str).str.strip()
master_df['MOBILE'] = master_df['MOBILE'].astype(str).str.strip()

# 3. Perform the Anti-Join
# We use 'left' to keep final_df records and 'indicator' to track matches
merged = final_df.merge(
    master_df[['MOBILE']], 
    left_on=['PHONE NO 1'], 
    right_on=[ 'MOBILE'], 
    how='left', 
    indicator=True
)


new_leads_df = merged[merged['_merge'] == 'left_only'].copy()

new_leads_df = new_leads_df.drop(columns=['_merge',  'MOBILE'])

new_leads_df = new_leads_df.drop_duplicates(subset=[ 'PHONE NO 1'])

print(f"Isolated {len(new_leads_df)} unique records not found in Master Data.")

# 7. Export to Excel
new_leads_df.to_excel("isolated_new_leads.xlsx", index=False)

Isolated 99 unique records not found in Master Data.

In [ ]:
# if not new_data_df.empty:
#     output_path = "New_Unsaved_Leads.xlsx"
#     new_data_df.to_excel(output_path, index=False)
#     print(f"Done! New records exported to {output_path}")
# else:
#     print("No new records found. Master data is already up to date.")